### ISSUE TITLE
[Bug] Doesn't supoort HVEC format

### ISSUE THREAD

**Issue by damsdev1** [Ipmake/PerPlexed#2] opened 2024-03-29 17:14 UTC
Your player doesn't support HVEC format and the player freeze and some errors appear in console.
You can also try to convert to a high resolution format when it doesn't support HVEC.

![image](https://github.com/Ipmake/PerPlexed/assets/60252259/95e08b75-f180-40d2-9fc3-495d23fa5fa0)

**Comment by FelixBorgel** [comment] 2024-05-17 11:21
Not Good

**Comment by FelOtt** [comment] 2024-10-09 07:27
Not good

**Comment by Ipmake** [comment] 2024-10-16 22:41
Could not reproduce, seems to be an issue with your media or has been resolved by now.
Im closing this issue for now, please test if the issue persists. If it does please report back.

**Closed by Ipmake** 2024-10-16 22:41 UTC
